### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by zhuozhuo** [tabsong/Tracking#1]
你好，你的经纬度文件，GuGoing.tracking。里面的数据是什么样的呢？我现在如果要把经纬度数据存储的话可以直接存储成数组格式么？

**Comment by tabsong** [comment]
1> GuGoing.tracking 内部数据格式是 CLLocationCoordinate2D \* 转换成 NSData
2> 存储成任何方式都可，只要能解析成 CLLocationCoordinate2D \* 即可.
