### ISSUE TITLE
gugongtracking文件如何生成的？

### ISSUE THREAD

**Issue by lynulzy** [tabsong/Tracking#2]

**Comment by tabsong** [comment]
1> GuGoing.tracking 内部数据格式是 CLLocationCoordinate2D \* 转换成 NSData
2> 存储成任何方式都可，只要能解析成 CLLocationCoordinate2D \* 即可.

**Comment by lynulzy** [comment]
嗯，已经用在项目里了，传入了一个coordinate数组。
