### ISSUE TITLE
抱歉，我还需要再问下关于位置数据数组的问题

### ISSUE THREAD

**Issue by lynulzy** [tabsong/Tracking#3]
我如此生成CLLocationCoordinate2D结构体，并添加到OC数组对象中

```
CLLocationCoordinate2D coor = CLLocationCoordinate2DMake([[dict objectForKey:@"latitude"] floatValue], [[dict objectForKey:@"longtitude"] floatValue]);
            [coordinates addObject:[NSValue value:&coor withObjCType:@encode(CLLocationCoordinate2D)]];
```

再将NSArray强转成CLLocationCoordinate2D *传入tracking对象中，并不能开始绘制路径，而且，地图页面会卡死，猜测是位置点数组的原因，麻烦lz帮忙解决

**Comment by lynulzy** [comment]
呼唤楼主@tabsong

**Comment by tabsong** [comment]
NSData *data = [NSData dataWithBytes:coordinates length:sizeof(CLLocationCoordinate2D) \* 3];
 BOOL writeSuccess = [data writeToFile:filePath atomically:YES];

**Comment by lynulzy** [comment]
非常感谢，参考您Demo中需要用malloc分配内存，解决了。

**Comment by guoqiaoHuang** [comment]
大哥，还是不知道怎么传数据啊 求指教@lynulzy,小弟qq903251914,谢谢

**Comment by tabsong** [comment]
@guoqiaoHuang 
1> Tracking类初始化方法是:
     - (instancetype)initWithCoordinates:(CLLocationCoordinate2D *)coordinates count:(NSUInteger)count;
     只需要传递一个CLLocationCoordinate2D 数组 和 个数就可以了，不需要纠结于GuGong.tracking 是如何生成的。

2> GuGong.tracking 文件生成代码如下:
    NSData *data = [NSData dataWithBytes:coordinates length:sizeof(CLLocationCoordinate2D) \* 3];
    BOOL writeSuccess = [data writeToFile:filePath atomically:YES];

**Comment by guoqiaoHuang** [comment]
CLLocationCoordinate2D这种类型的 数组吗

**Comment by tabsong** [comment]
@guoqiaoHuang YES
