### ISSUE TITLE
没有跟随轨迹的ball图像

### ISSUE THREAD

**Issue by lynulzy** [tabsong/Tracking#4]
按照Demo我如此生成了tracking对象
    trackingRoute_ = [[Tracking alloc] initWithCoordinates:theCoordinates count:cnt];
    trackingRoute_.delegate = self;
    trackingRoute_.mapView = mapView_;
    trackingRoute_.duration = 5.0f;
    trackingRoute_.edgeInsets = UIEdgeInsetsMake(50, 50, 50, 50);
    [trackingRoute_ execute];

并且在annotationView的代理方法中生成了annotationview

 if (annotation == trackingRoute_.annotation)
    {
        static NSString *trackingReuseIndetifier = @"trackingReuseIndetifier";

```
    MAAnnotationView *annotationView = [mapView dequeueReusableAnnotationViewWithIdentifier:trackingReuseIndetifier];

    if (annotationView == nil)
    {
        annotationView = [[MAAnnotationView alloc] initWithAnnotation:annotation reuseIdentifier:trackingReuseIndetifier];
    }

    annotationView.canShowCallout = NO;
    annotationView.image = [UIImage imageNamed:IMG_NAME_TRACKING_ANNOTATION];

    return annotationView;
}
```

但是在轨迹执行过程中，这个ball并不会跟着轨迹走，而是在绘制完成之后才静态的出现。

So 问题来了，如何是ball跟随轨迹运动？

**Comment by tabsong** [comment]
Demo 可以, 你的也可以，仔细看看代码，若还是不行的话，你写个简单的Demo, 发到我的邮箱tabsong2012@gmail.com. 我帮你看看。

**Comment by lynulzy** [comment]
我再仔细研究一下，回归测试测到这了，前面一直没解决。

**Comment by tabsong** [comment]
close this issue
