### ISSUE TITLE
是否可以实时监控

### ISSUE THREAD

**Issue by Fengur** [tabsong/Tracking#6]

**Comment by tabsong** [comment]
实时监控什么呢? 说的详细一些。

**Comment by Fengur** [comment]
很久以前的东西了，我都忘了。

原始邮件
发件人:tabsongnotifications@github.com
收件人:tabsong/TrackingTracking@noreply.github.com
抄送:Duraedreamduraedream@gmail.com; Authorauthor@noreply.github.com
发送时间:2016年9月22日(周四) 15:51
主题:Re: [tabsong/Tracking] 是否可以实时监控 (#6)

实时监控什么呢? 说的详细一些。
